"""made authorization

Revision ID: 077a613eadcd
Revises: 457ffa945bc1
Create Date: 2023-04-12 17:44:01.221117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077a613eadcd'
down_revision = '457ffa945bc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
