"""Add data in table Operations

Revision ID: 1c040aafc352
Revises: a77c9cc26bba
Create Date: 2023-05-09 19:40:47.969622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c040aafc352'
down_revision = 'a77c9cc26bba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
