"""change types

Revision ID: 27fc5c98a9d4
Revises: d9e9e765a3a7
Create Date: 2023-07-06 14:44:06.672975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fc5c98a9d4'
down_revision = 'd9e9e765a3a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
