"""change tables, add autoincrement

Revision ID: 5e368853062f
Revises: 4c5945a2ef18
Create Date: 2023-07-01 21:31:10.702285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e368853062f'
down_revision = '4c5945a2ef18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
