"""add token in table

Revision ID: 800397b4740e
Revises: 128639addd88
Create Date: 2023-07-04 23:37:58.432715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800397b4740e'
down_revision = '128639addd88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_token')
    # ### end Alembic commands ###
