"""add show database

Revision ID: 8a5ef05984a0
Revises: a5b5ca872907
Create Date: 2023-05-09 20:17:54.248655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5ef05984a0'
down_revision = 'a5b5ca872907'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
