"""change

Revision ID: 99ab950256f6
Revises: 27fc5c98a9d4
Create Date: 2023-07-06 15:31:09.801594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ab950256f6'
down_revision = '27fc5c98a9d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
