"""Add data in table

Revision ID: a5b5ca872907
Revises: 1c040aafc352
Create Date: 2023-05-09 19:47:54.674083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b5ca872907'
down_revision = '1c040aafc352'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
