"""change database tables

Revision ID: aba89db5bfe0
Revises: c449c62e52b4
Create Date: 2023-06-25 17:57:05.546482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aba89db5bfe0'
down_revision = 'c449c62e52b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('salary', sa.Float(), nullable=False))
    op.drop_column('role', 'name')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'registered_at')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('role', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('role', 'salary')
    # ### end Alembic commands ###
