"""delete fields response

Revision ID: d9e9e765a3a7
Revises: bd5f67c10ada
Create Date: 2023-07-06 00:54:56.193149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e9e765a3a7'
down_revision = 'bd5f67c10ada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
